### ISSUE TITLE
More Output

### ISSUE THREAD

**Issue by maximilian-kruse** [linusseelinger/mtmc#7]
Especially for debugging purposes, it would be useful to generate more output. I wouldn't clutter the standard logger with this, though. Right now, I am thinking of something like a separate debug log that can be activated by the user.

Possibly useful output:
- [x] MTree visualization after new node generation
- [x] MTree after retrieval of posterior evaluations
- [x] MTree after pruning
- [x] Accept rate estimates after generation of new samples
- [x] Posterior evaluations
- [x] Number of created and deleted nodes, tree size
- [x] Current configuration of a model
- [x] result of accept-reject step

**Comment by sebwolf-de** [comment]
Hi,
I'd appreciate a debug output in the form:
```
Evaluate forward model with parameters {parameters} and config {config}: {result}, accepted {accepted}
```

**Comment by maximilian-kruse** [comment]
Noted, I will get to that asap
